# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MapDemo' do
  pod 'Mapbox-iOS-SDK', '~> 3.2.3'
  pod 'RealmSwift'
  pod 'ObjectMapper', '~> 1.3'
  pod "CheapRulerIOS"
end

target 'MapDemoTests' do

end

target 'MapDemoUITests' do

end

